trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: 1.3.6
      terraformPath: terraform
      servicePrinciple: petteri-test-sub
      containerName: terraform
      storageAccountName: samobitf
      resourceGroupName: terraformstate-rg
      action: destroy