trigger:
  - "*"

pool:
  vmImage: "ubuntu-latest"

steps:
  - pwsh: |
      $name = "$(Build.SourceBranch)" -replace 'refs/heads/'
      Write-Host "Name was: $name"
    displayName: Check branch name

  - template: terraform.yml
    parameters:
      terraformVersion: 1.3.6
      terraformPath: terraform
      servicePrinciple: petteri-test-sub
      containerName: terraform
      storageAccountName: samobitf
      resourceGroupName: terraformstate-rg
