trigger:
  - "*"

pool:
  vmImage: "ubuntu-latest"

steps:
  - pwsh: |
      $name = "$(Build.SourceBranch)" -replace 'refs/heads/'

      if ($name -ne 'main' ) {
        Write-Host "##vso[task.setvariable variable=TF_VAR_branch;]$name"
      } else {
        Write-Host "main branch"
      }
    displayName: Check branch name

  - template: terraform.yml
    parameters:
      terraformVersion: 1.3.6
      terraformPath: terraform
      servicePrinciple: petteri-test-sub
      containerName: terraform
      storageAccountName: samobitf
      workspace: $(TF_VAR_branch)
      resourceGroupName: terraformstate-rg
